apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-deployement
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mvc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mvc
    spec:
      containers:
      - image: onshanafi/productstoreonkubs:v1.0
        name: mvc
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mvc-service
spec:
  selector:
    app: mvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30100
  type: NodePort

