apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: mvc
  template:
    metadata:
      labels:
        name: mvc
    spec:
      containers:
      - image: onshanafi/productstoreonkubs:v1.0
        name: mvc
        ports:
        - containerPort: 80
        env:
         - name: "ASPNETCORE_ENVIRONMENT"
           value: "Development"
         - name: ConnectionStrings__ProductContext
           value: Server=mssql-service;Database=ProductDB;User=SA;Password=@Aa123456; 
---
apiVersion: v1
kind: Service
metadata:
  name: mvc-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30100
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: mvc
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

